# secrets/podManifestVolume.yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod 
spec:
  restartPolicy: Never
  containers:
    - name: alpine 
      image: alpine
      args: ["sh","-c","ls -l /var/config"]
      volumeMounts:
        - name: my-volume
          mountPath: /var/config
  volumes: 
    - name: my-volume 
      secret: # rather than configMap
        secretName: my-secrets # rather than name

