# simpleDeployment.yaml
apiVersion: apps/v1   
kind: Deployment
metadata:
  name: nginx-declarative
spec:
  strategy: 
    type: Recreate
  replicas: 6          # Specify number of replicas
  selector:
    matchLabels:       # Select Embedded Pod 
      app: nginx-app 
  template:            # Embedded Pod Template
    metadata:
      labels:
        app: nginx-app 
    spec:
      containers:      
      - name: nginx-container
        image: nginx:1.22-perl