# nginx-self-healing.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-self-healing
spec:
  containers:
  - image: nginx
    name: nginx
    readinessProbe:
      exec:
        command:
        - /bin/cat 
        - /ready.txt
      initialDelaySeconds: 15 # Wait before starting the probe
      timeoutSeconds: 1       # Tolerate latency (e.g., slow web server)
      periodSeconds: 15       # How long to wait before polling again
      failureThreshold: 3    # Number of failures before flagging as not live 
      successThreshold: 1     # Number of successes before clearing failure count 
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
      initialDelaySeconds: 5 # Wait before starting the probe
      timeoutSeconds: 1      # Tolerate latency (e.g., slow web server)
      periodSeconds: 10      # How long to wait before polling again
      failureThreshold: 3    # Number of failures before flagging as not live 
      successThreshold: 1    # Number of successes before clearing failure count     
  restartPolicy: Always
