# nginx-probes.yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    readinessProbe:
      exec:
        command:
        - /bin/cat 
        - /ready.txt
    livenessProbe:
      httpGet:
        path: /index.html
        port: 80
  restartPolicy: Always
