apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: hello
  labels:
    cronjob-group: hello
spec:
  schedule: "*/2 * * * 3" # "*/1 * * * *"
  successfulJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template: # necessary to see Pods
        metadata:
          labels:
            cronjob-group: hello
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
