# podManifestWithArgVariables.yaml
apiVersion: v1
kind: Pod
metadata:
  name: my-pod 
spec:
  restartPolicy: Never
  containers:
    - name: alpine 
      image: alpine
      args: 
      - /bin/sh
      - -c
      - echo Hello $(mysql_host)
      envFrom:
      - configMapRef:
          name: data-sources