apiVersion: v1
kind: ConfigMap
metadata:
  name: greeting
data:
  hello.en: Hello
  hello.it: Ciao
  hello.pt: Ola
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
    - name: nginx
      image: nginx
      # command: [ "/bin/sh", "-c", "env" ]
      env:
        # Define the environment variable
        - name: GREETING_ES
          value: Hola
        - name: GREETING_IT
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: greeting
              # Specify the key associated with the value
              key: hello.it
        - name: GREETING_PT
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: greeting
              # Specify the key associated with the value
              key: hello.pt
  restartPolicy: Never