# nginx-limited.yaml
apiVersion: apps/v1   
kind: Deployment
metadata:
  name: nginx-declarative
spec:
  replicas: 1          # Specify number of replicas
  selector:
    matchLabels:       # Select Embedded Pod 
      app: nginx-app 
  template:            # Embedded Pod Template
    metadata:
      labels:
        app: nginx-app 
    spec:
      containers:      
      - name: nginx-container
        image: nginx:1.22.0
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "100m"
