# service.yaml
kind: Service
apiVersion: v1
metadata:
  name: nginx2    # To avoid collision with imperative version
spec:
  selector:
    app: nginx    # Must match Pod label!
  ports:
  - protocol: TCP
    port: 80
 
