# logCompressorClient.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client2
spec:
  replicas: 7
  selector:
    matchLabels:
      app: client2 
  template:
    metadata:
      labels:
        app: client2
    spec:
      volumes:
      - name: logdir
        hostPath:
          path: /var/log
      containers:
      - name: client2
        image: alpine 
        volumeMounts:
         - name: logdir
           mountPath: /var/log     
        args: 
        - /bin/sh
        - -c
        - >-
          while true; 
          do echo $(date) - 
          Greetings from $HOSTNAME >> 
          /var/log/$HOSTNAME.log; 
          sleep 15; 
          done
